### ISSUE TITLE
Compiler and OTP Server

### ISSUE THREAD

**Issue by ttpeppermint2011** [CodeAnGo/TT2#1]
### @CodeAnGo Hello, CodeAnGo! I would like to request the compiler and OTP server for my Toontown related project. Thank you and have a toontastic day! :slightly_smiling_face:

**Comment by ponyboy837** [comment]
What? Why would you need one? Just use Astron and Nirai. We don't even know what your project is. So why make a OTP for a project that could just back-stab the people who made it in the long run?

**Comment by ttpeppermint2011** [comment]
I wouldn't back-stab the people who made this Toontown source code. I would give credit to the people of Toontropolis Studios. I've never leaked a source code and never would. Anyways, on to the reason why I want to use this source code. First of all, I don't know if this will fit my Toontown related project or not because I'm working on a Toontown server with a vanilla Toontown Online experience with a few tweaks. If this does fit my project needs. You can send me the compiler and the OTP server if you want too. If this doesn't fit my project needs. You can close this issue and I will accept that this server isn't what I need for my project. Thank you, for the response, @ponyboy837 :slightly_smiling_face:!

**Comment by SkippsDev** [comment]
Look this is why you don't release private projects. Shit like this happens.
